baseURL = 'tofudreams.com/'
languageCode = 'en-us'
title = 'Tofu Dreams'
description = "Vegan recipes to dream about"
copyright = "2024 Tofu Dreams"
theme = 'bean'

relativeURLs = true
summaryLength = 10
paginate = 12
capitalizeListTitles = false

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    tag = "tags"
    category = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Savory"
    pre = "savory"
    pageref = "/categories/savory/"
    weight = 2
  [[menu.main]]
    name = "Sweet"
    pre = "sweet"
    pageref = "/categories/sweet/"
    weight = 3
  [[menu.main]]
    name = "Oatmeal"
    pre = "oatmeal"
    pageref = "/categories/oatmeal/"
    weight = 4

[params]
  logo = "logo.png"
  icon = "favicon.png"
  name = "Tofu Dreams"
  description = "Vegan recipes to dream about"
